# Generated by Django 3.1.7 on 2021-03-18 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watches', '0003_auto_20210318_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watch',
            name='description',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='watch',
            name='watch_brand',
            field=models.CharField(choices=[('ROLEX', 'ROLEX'), ('OMEGA', 'OMEGA'), ('HUBLOT', 'HUBLOT')], default='ROLEX', max_length=30),
        ),
        migrations.AlterField(
            model_name='watch',
            name='watch_model',
            field=models.CharField(max_length=100),
        ),
    ]
