# Generated by Django 3.1.7 on 2021-03-18 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watches', '0005_watch_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watch',
            name='price',
            field=models.IntegerField(),
        ),
    ]
